// <auto-generated />
using System;
using Com.Danliris.Service.Packing.Inventory.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Com.Danliris.Service.Packing.Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(PackingInventoryDbContext))]
    partial class PackingInventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.ProductSKUModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Code")
                        .HasMaxLength(32);

                    b.Property<string>("Composition")
                        .HasMaxLength(128);

                    b.Property<string>("Construction")
                        .HasMaxLength(128);

                    b.Property<string>("CreatedAgent");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("Currency")
                        .HasMaxLength(1024);

                    b.Property<string>("DeletedAgent");

                    b.Property<string>("DeletedBy");

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<string>("Description")
                        .HasMaxLength(1024);

                    b.Property<string>("Design")
                        .HasMaxLength(128);

                    b.Property<string>("Grade")
                        .HasMaxLength(32);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<string>("Lot")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<decimal>("Price");

                    b.Property<string>("ProductType")
                        .HasMaxLength(32);

                    b.Property<string>("SKUCode")
                        .HasMaxLength(32);

                    b.Property<string>("SKUId")
                        .HasMaxLength(128);

                    b.Property<string>("Tags")
                        .HasMaxLength(512);

                    b.Property<string>("UOM")
                        .HasMaxLength(1024);

                    b.Property<string>("Width")
                        .HasMaxLength(128);

                    b.Property<string>("WovenType")
                        .HasMaxLength(128);

                    b.Property<string>("YarnType1")
                        .HasMaxLength(128);

                    b.Property<string>("YarnType2")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("ProductSKUs");
                });
#pragma warning restore 612, 618
        }
    }
}
