// <auto-generated />
using System;
using Com.Danliris.Service.Packing.Inventory.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Com.Danliris.Service.Packing.Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(PackingInventoryDbContext))]
    [Migration("20200605093727_Refactor")]
    partial class Refactor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.DyeingPrintingAreaMovement.DyeingPrintingAreaInputModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Area")
                        .HasMaxLength(64);

                    b.Property<string>("BonNo")
                        .HasMaxLength(64);

                    b.Property<string>("CreatedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<DateTimeOffset>("Date");

                    b.Property<string>("DeletedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<string>("Group")
                        .HasMaxLength(16);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<string>("Shift")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("DyeingPrintingAreaInputs");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.DyeingPrintingAreaMovement.DyeingPrintingAreaInputProductionOrderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Area")
                        .HasMaxLength(64);

                    b.Property<double>("AvalALength");

                    b.Property<double>("AvalBLength");

                    b.Property<string>("AvalCartNo");

                    b.Property<double>("AvalConnectionLength");

                    b.Property<double>("AvalQuantityKg");

                    b.Property<string>("AvalType");

                    b.Property<double>("Balance");

                    b.Property<decimal>("BalanceRemains")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 38, scale: 17)))
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Buyer")
                        .HasMaxLength(4096);

                    b.Property<int>("BuyerId");

                    b.Property<string>("CartNo")
                        .HasMaxLength(128);

                    b.Property<string>("Color")
                        .HasMaxLength(4096);

                    b.Property<string>("Construction")
                        .HasMaxLength(1024);

                    b.Property<string>("CreatedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<long>("DeliveryOrderSalesId");

                    b.Property<string>("DeliveryOrderSalesNo")
                        .HasMaxLength(128);

                    b.Property<int>("DyeingPrintingAreaInputId");

                    b.Property<string>("Grade")
                        .HasMaxLength(128);

                    b.Property<bool>("HasOutputDocument");

                    b.Property<double>("InitLength");

                    b.Property<bool>("IsChecked");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<string>("Motif")
                        .HasMaxLength(4096);

                    b.Property<decimal>("PackagingQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PackagingType")
                        .HasMaxLength(128);

                    b.Property<string>("PackagingUnit")
                        .HasMaxLength(128);

                    b.Property<string>("PackingInstruction")
                        .HasMaxLength(4096);

                    b.Property<long>("ProductionOrderId");

                    b.Property<string>("ProductionOrderNo")
                        .HasMaxLength(128);

                    b.Property<double>("ProductionOrderOrderQuantity");

                    b.Property<string>("ProductionOrderType")
                        .HasMaxLength(512);

                    b.Property<string>("Remark")
                        .HasMaxLength(128);

                    b.Property<string>("Status")
                        .HasMaxLength(128);

                    b.Property<string>("Unit")
                        .HasMaxLength(4096);

                    b.Property<string>("UomUnit")
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.HasIndex("DyeingPrintingAreaInputId");

                    b.ToTable("DyeingPrintingAreaInputProductionOrders");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.DyeingPrintingAreaMovement.DyeingPrintingAreaMovementModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Area")
                        .HasMaxLength(128);

                    b.Property<double>("Balance");

                    b.Property<string>("Buyer")
                        .HasMaxLength(4096);

                    b.Property<string>("CartNo")
                        .HasMaxLength(128);

                    b.Property<string>("Color")
                        .HasMaxLength(4096);

                    b.Property<string>("Construction")
                        .HasMaxLength(1024);

                    b.Property<string>("CreatedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<DateTimeOffset>("Date");

                    b.Property<string>("DeletedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<string>("DyeingPrintingAreaDocumentBonNo")
                        .HasMaxLength(64);

                    b.Property<int>("DyeingPrintingAreaDocumentId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<string>("Motif")
                        .HasMaxLength(4096);

                    b.Property<long>("ProductionOrderId");

                    b.Property<string>("ProductionOrderNo")
                        .HasMaxLength(128);

                    b.Property<string>("Type")
                        .HasMaxLength(32);

                    b.Property<string>("Unit")
                        .HasMaxLength(4096);

                    b.Property<string>("UomUnit")
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.ToTable("DyeingPrintingAreaMovements");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.DyeingPrintingAreaMovement.DyeingPrintingAreaOutputAvalItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<int>("DyeingPrintingAreaOutputProductionOrderId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<double>("Length");

                    b.Property<string>("Type")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.HasIndex("DyeingPrintingAreaOutputProductionOrderId");

                    b.ToTable("DyeingPrintingAreaOutputAvalItems");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.DyeingPrintingAreaMovement.DyeingPrintingAreaOutputModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Area")
                        .HasMaxLength(64);

                    b.Property<string>("BonNo")
                        .HasMaxLength(64);

                    b.Property<string>("CreatedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<DateTimeOffset>("Date");

                    b.Property<string>("DeletedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<long>("DeliveryOrderSalesId");

                    b.Property<string>("DeliveryOrderSalesNo")
                        .HasMaxLength(128);

                    b.Property<string>("DestinationArea")
                        .HasMaxLength(64);

                    b.Property<string>("Group")
                        .HasMaxLength(16);

                    b.Property<bool>("HasNextAreaDocument");

                    b.Property<bool>("HasSalesInvoice");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<string>("Shift")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("DyeingPrintingAreaOutputs");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.DyeingPrintingAreaMovement.DyeingPrintingAreaOutputProductionOrderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Area")
                        .HasMaxLength(64);

                    b.Property<double>("AvalALength");

                    b.Property<double>("AvalBLength");

                    b.Property<string>("AvalCartNo");

                    b.Property<double>("AvalConnectionLength");

                    b.Property<double>("AvalQuantityKg");

                    b.Property<string>("AvalType");

                    b.Property<double>("Balance");

                    b.Property<string>("Buyer")
                        .HasMaxLength(4096);

                    b.Property<int>("BuyerId");

                    b.Property<string>("CartNo")
                        .HasMaxLength(128);

                    b.Property<string>("Color")
                        .HasMaxLength(4096);

                    b.Property<string>("Construction")
                        .HasMaxLength(1024);

                    b.Property<string>("CreatedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<string>("DeliveryNote")
                        .HasMaxLength(128);

                    b.Property<long>("DeliveryOrderSalesId");

                    b.Property<string>("DeliveryOrderSalesNo")
                        .HasMaxLength(128);

                    b.Property<string>("Description")
                        .HasMaxLength(4096);

                    b.Property<string>("DestinationArea")
                        .HasMaxLength(64);

                    b.Property<int>("DyeingPrintingAreaInputProductionOrderId")
                        .HasMaxLength(128);

                    b.Property<int>("DyeingPrintingAreaOutputId");

                    b.Property<string>("Grade")
                        .HasMaxLength(128);

                    b.Property<bool>("HasNextAreaDocument");

                    b.Property<bool>("HasSalesInvoice");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<string>("Motif")
                        .HasMaxLength(4096);

                    b.Property<decimal>("PackagingQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PackagingType")
                        .HasMaxLength(128);

                    b.Property<string>("PackagingUnit")
                        .HasMaxLength(128);

                    b.Property<string>("PackingInstruction")
                        .HasMaxLength(4096);

                    b.Property<long>("ProductionOrderId");

                    b.Property<string>("ProductionOrderNo")
                        .HasMaxLength(128);

                    b.Property<double>("ProductionOrderOrderQuantity");

                    b.Property<string>("ProductionOrderType")
                        .HasMaxLength(512);

                    b.Property<string>("Remark")
                        .HasMaxLength(128);

                    b.Property<string>("ShippingGrade")
                        .HasMaxLength(128);

                    b.Property<string>("ShippingRemark")
                        .HasMaxLength(512);

                    b.Property<string>("Status")
                        .HasMaxLength(128);

                    b.Property<string>("Unit")
                        .HasMaxLength(4096);

                    b.Property<string>("UomUnit")
                        .HasMaxLength(32);

                    b.Property<double>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("DyeingPrintingAreaOutputId");

                    b.ToTable("DyeingPrintingAreaOutputProductionOrders");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.DyeingPrintingAreaMovement.DyeingPrintingAreaSummaryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Area")
                        .HasMaxLength(128);

                    b.Property<double>("Balance");

                    b.Property<string>("Buyer")
                        .HasMaxLength(4096);

                    b.Property<string>("CartNo")
                        .HasMaxLength(128);

                    b.Property<string>("Color")
                        .HasMaxLength(4096);

                    b.Property<string>("Construction")
                        .HasMaxLength(1024);

                    b.Property<string>("CreatedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<DateTimeOffset>("Date");

                    b.Property<string>("DeletedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<string>("DyeingPrintingAreaDocumentBonNo")
                        .HasMaxLength(64);

                    b.Property<int>("DyeingPrintingAreaDocumentId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<string>("Motif")
                        .HasMaxLength(4096);

                    b.Property<long>("ProductionOrderId");

                    b.Property<string>("ProductionOrderNo")
                        .HasMaxLength(128);

                    b.Property<string>("Type")
                        .HasMaxLength(32);

                    b.Property<string>("Unit")
                        .HasMaxLength(4096);

                    b.Property<string>("UomUnit")
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.ToTable("DyeingPrintingAreaSummaries");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.FabricQualityControl.CriteriaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasMaxLength(32);

                    b.Property<int>("FabricGradeTestId");

                    b.Property<string>("Group")
                        .HasMaxLength(4096);

                    b.Property<int>("Index");

                    b.Property<string>("Name")
                        .HasMaxLength(4096);

                    b.Property<double>("ScoreA");

                    b.Property<double>("ScoreB");

                    b.Property<double>("ScoreC");

                    b.Property<double>("ScoreD");

                    b.HasKey("Id");

                    b.HasIndex("FabricGradeTestId");

                    b.ToTable("NewCriterias");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.FabricQualityControl.FabricGradeTestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<double>("AvalALength");

                    b.Property<double>("AvalBLength");

                    b.Property<double>("AvalConnectionLength");

                    b.Property<string>("CreatedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<double>("FabricGradeTest");

                    b.Property<int>("FabricQualityControlId");

                    b.Property<double>("FinalArea");

                    b.Property<double>("FinalGradeTest");

                    b.Property<double>("FinalLength");

                    b.Property<double>("FinalScore");

                    b.Property<string>("Grade")
                        .HasMaxLength(512);

                    b.Property<double>("InitLength");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("ItemIndex");

                    b.Property<string>("LastModifiedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<string>("PcsNo")
                        .HasMaxLength(4096);

                    b.Property<double>("PointLimit");

                    b.Property<double>("PointSystem");

                    b.Property<double>("SampleLength");

                    b.Property<double>("Score");

                    b.Property<string>("Type")
                        .HasMaxLength(1024);

                    b.Property<double>("Width");

                    b.HasKey("Id");

                    b.HasIndex("FabricQualityControlId");

                    b.ToTable("NewFabricGradeTests");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.FabricQualityControl.FabricQualityControlModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Code")
                        .HasMaxLength(32);

                    b.Property<string>("CreatedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<DateTimeOffset>("DateIm");

                    b.Property<string>("DeletedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<string>("DyeingPrintingAreaInputBonNo")
                        .HasMaxLength(64);

                    b.Property<int>("DyeingPrintingAreaInputId");

                    b.Property<int>("DyeingPrintingAreaInputProductionOrderId");

                    b.Property<string>("Group")
                        .HasMaxLength(4096);

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsUsed");

                    b.Property<string>("LastModifiedAgent")
                        .HasMaxLength(128);

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(128);

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<string>("MachineNoIm")
                        .HasMaxLength(4096);

                    b.Property<string>("OperatorIm")
                        .HasMaxLength(4096);

                    b.Property<double>("PointLimit");

                    b.Property<double>("PointSystem");

                    b.Property<string>("ProductionOrderNo")
                        .HasMaxLength(128);

                    b.Property<string>("UId")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("NewFabricQualityControls");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.Inventory.ProductPackingInventoryDocumentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedAgent");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<DateTimeOffset>("Date");

                    b.Property<string>("DeletedAgent");

                    b.Property<string>("DeletedBy");

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<string>("DocumentNo")
                        .HasMaxLength(64);

                    b.Property<string>("InventoryType")
                        .HasMaxLength(32);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(64);

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(256);

                    b.Property<string>("Remark");

                    b.Property<string>("StorageCode")
                        .HasMaxLength(64);

                    b.Property<int>("StorageId");

                    b.Property<string>("StorageName")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.ToTable("ProductPackingInventoryDocuments");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.Inventory.ProductPackingInventoryMovementModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedAgent");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent");

                    b.Property<string>("DeletedBy");

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<int>("InventoryDocumentId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<int>("ProductSKUId");

                    b.Property<double>("Quantity");

                    b.Property<string>("Remark");

                    b.Property<int>("UOMId");

                    b.HasKey("Id");

                    b.ToTable("ProductPackingInventoryMovements");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.Inventory.ProductPackingInventorySummaryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedAgent");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent");

                    b.Property<string>("DeletedBy");

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<int>("ProductPackingId");

                    b.Property<double>("Quantity");

                    b.Property<string>("StorageCode")
                        .HasMaxLength(64);

                    b.Property<int>("StorageId");

                    b.Property<string>("StorageName")
                        .HasMaxLength(512);

                    b.Property<int>("UOMId");

                    b.HasKey("Id");

                    b.ToTable("ProductPackingInventorySummaries");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.Inventory.ProductSKUInventoryDocumentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedAgent");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<DateTimeOffset>("Date");

                    b.Property<string>("DeletedAgent");

                    b.Property<string>("DeletedBy");

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<string>("DocumentNo")
                        .HasMaxLength(64);

                    b.Property<string>("InventoryType")
                        .HasMaxLength(32);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(64);

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(256);

                    b.Property<string>("Remark");

                    b.Property<string>("StorageCode")
                        .HasMaxLength(64);

                    b.Property<int>("StorageId");

                    b.Property<string>("StorageName")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.ToTable("ProductSKUInventoryDocuments");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.Inventory.ProductSKUInventoryMovementModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedAgent");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent");

                    b.Property<string>("DeletedBy");

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<int>("InventoryDocumentId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<int>("ProductSKUId");

                    b.Property<double>("Quantity");

                    b.Property<string>("Remark");

                    b.Property<int>("UOMId");

                    b.HasKey("Id");

                    b.ToTable("ProductSKUInventoryMovements");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.Inventory.ProductSKUInventorySummaryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedAgent");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent");

                    b.Property<string>("DeletedBy");

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<int>("ProductSKUId");

                    b.Property<double>("Quantity");

                    b.Property<string>("StorageCode")
                        .HasMaxLength(64);

                    b.Property<int>("StorageId");

                    b.Property<string>("StorageName")
                        .HasMaxLength(256);

                    b.Property<int>("UOMId");

                    b.HasKey("Id");

                    b.ToTable("ProductSKUInventorySummaries");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.Product.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Code")
                        .HasMaxLength(64);

                    b.Property<string>("CreatedAgent");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent");

                    b.Property<string>("DeletedBy");

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<string>("Name")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("IPCategories");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.Product.ProductPackingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Code")
                        .HasMaxLength(64);

                    b.Property<string>("CreatedAgent");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent");

                    b.Property<string>("DeletedBy");

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<string>("Name")
                        .HasMaxLength(512);

                    b.Property<double>("PackingSize");

                    b.Property<int>("ProductSKUId");

                    b.Property<int>("UOMId");

                    b.HasKey("Id");

                    b.ToTable("ProductPackings");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.Product.ProductSKUModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<int>("CategoryId");

                    b.Property<string>("Code")
                        .HasMaxLength(64);

                    b.Property<string>("CreatedAgent");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent");

                    b.Property<string>("DeletedBy");

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<string>("Name")
                        .HasMaxLength(512);

                    b.Property<int>("UOMId");

                    b.HasKey("Id");

                    b.ToTable("ProductSKUs");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.Product.UnitOfMeasurementModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedAgent");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent");

                    b.Property<string>("DeletedBy");

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<string>("Unit")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("IPUnitOfMeasurements");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.ProductByDivisionOrCategory.FabricProductPackingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Code")
                        .HasMaxLength(64);

                    b.Property<string>("CreatedAgent");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent");

                    b.Property<string>("DeletedBy");

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<int>("FabricProductSKUId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<double>("PackingSize");

                    b.Property<int>("ProductPackingId");

                    b.Property<int>("ProductSKUId");

                    b.Property<string>("UOMUnit")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("FabricProductPackings");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.ProductByDivisionOrCategory.FabricProductSKUModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Code")
                        .HasMaxLength(64);

                    b.Property<string>("Composition")
                        .HasMaxLength(128);

                    b.Property<string>("Construction")
                        .HasMaxLength(128);

                    b.Property<string>("CreatedAgent");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent");

                    b.Property<string>("DeletedBy");

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<string>("Design")
                        .HasMaxLength(64);

                    b.Property<string>("Grade")
                        .HasMaxLength(32);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<int>("ProductSKUId");

                    b.Property<string>("UOMUnit")
                        .HasMaxLength(64);

                    b.Property<string>("Width")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("FabricProductSKUs");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.ProductByDivisionOrCategory.GreigeProductPackingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Code")
                        .HasMaxLength(64);

                    b.Property<string>("CreatedAgent");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent");

                    b.Property<string>("DeletedBy");

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<int>("GreigeProductSKUId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<double>("PackingSize");

                    b.Property<int>("ProductPackingId");

                    b.Property<int>("ProductSKUId");

                    b.Property<string>("UOMUnit")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("GreigeProductPackings");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.ProductByDivisionOrCategory.GreigeProductSKUModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Code")
                        .HasMaxLength(64);

                    b.Property<string>("Construction")
                        .HasMaxLength(128);

                    b.Property<string>("CreatedAgent");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent");

                    b.Property<string>("DeletedBy");

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<string>("Grade")
                        .HasMaxLength(32);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<string>("UOMUnit")
                        .HasMaxLength(64);

                    b.Property<string>("Warp")
                        .HasMaxLength(64);

                    b.Property<string>("Weft")
                        .HasMaxLength(64);

                    b.Property<string>("Width")
                        .HasMaxLength(64);

                    b.Property<string>("WovenType")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("GreigeProductSKUs");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.ProductByDivisionOrCategory.YarnProductPackingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Code")
                        .HasMaxLength(64);

                    b.Property<string>("CreatedAgent");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent");

                    b.Property<string>("DeletedBy");

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<double>("PackingSize");

                    b.Property<int>("ProductPackingId");

                    b.Property<int>("ProductSKUId");

                    b.Property<string>("UOMUnit")
                        .HasMaxLength(64);

                    b.Property<int>("YarnProductSKUId");

                    b.HasKey("Id");

                    b.ToTable("YarnProductPackings");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.ProductByDivisionOrCategory.YarnProductSKUModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Code")
                        .HasMaxLength(64);

                    b.Property<string>("CreatedAgent");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent");

                    b.Property<string>("DeletedBy");

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<string>("LotNo")
                        .HasMaxLength(128);

                    b.Property<int>("ProductSKUId");

                    b.Property<string>("UOMUnit")
                        .HasMaxLength(64);

                    b.Property<string>("YarnType")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("YarnProductSKUs");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.DyeingPrintingAreaMovement.DyeingPrintingAreaInputProductionOrderModel", b =>
                {
                    b.HasOne("Com.Danliris.Service.Packing.Inventory.Data.Models.DyeingPrintingAreaMovement.DyeingPrintingAreaInputModel", "DyeingPrintingAreaInput")
                        .WithMany("DyeingPrintingAreaInputProductionOrders")
                        .HasForeignKey("DyeingPrintingAreaInputId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.DyeingPrintingAreaMovement.DyeingPrintingAreaOutputAvalItemModel", b =>
                {
                    b.HasOne("Com.Danliris.Service.Packing.Inventory.Data.Models.DyeingPrintingAreaMovement.DyeingPrintingAreaOutputProductionOrderModel", "DyeingPrintingAreaOutputProductionOrder")
                        .WithMany("DyeingPrintingAreaOutputAvalItems")
                        .HasForeignKey("DyeingPrintingAreaOutputProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.DyeingPrintingAreaMovement.DyeingPrintingAreaOutputProductionOrderModel", b =>
                {
                    b.HasOne("Com.Danliris.Service.Packing.Inventory.Data.Models.DyeingPrintingAreaMovement.DyeingPrintingAreaOutputModel", "DyeingPrintingAreaOutput")
                        .WithMany("DyeingPrintingAreaOutputProductionOrders")
                        .HasForeignKey("DyeingPrintingAreaOutputId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.FabricQualityControl.CriteriaModel", b =>
                {
                    b.HasOne("Com.Danliris.Service.Packing.Inventory.Data.Models.FabricQualityControl.FabricGradeTestModel", "FabricGradeTest")
                        .WithMany("Criteria")
                        .HasForeignKey("FabricGradeTestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.FabricQualityControl.FabricGradeTestModel", b =>
                {
                    b.HasOne("Com.Danliris.Service.Packing.Inventory.Data.Models.FabricQualityControl.FabricQualityControlModel", "FabricQualityControl")
                        .WithMany("FabricGradeTests")
                        .HasForeignKey("FabricQualityControlId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
