// <auto-generated />
using System;
using Com.Danliris.Service.Packing.Inventory.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Com.Danliris.Service.Packing.Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(PackingInventoryDbContext))]
    partial class PackingInventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.PackagingInventoryDocumentItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedAgent");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent");

                    b.Property<string>("DeletedBy");

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<string>("Packaging")
                        .HasMaxLength(1024);

                    b.Property<int>("PackagingId");

                    b.Property<int>("PackagingInventoryDocumentId");

                    b.Property<int?>("PackagingIventoryDocumentId");

                    b.Property<decimal>("Quantity");

                    b.Property<string>("Remark")
                        .HasMaxLength(1024);

                    b.Property<string>("SKU")
                        .HasMaxLength(1024);

                    b.Property<int>("SKUId");

                    b.HasKey("Id");

                    b.HasIndex("PackagingIventoryDocumentId");

                    b.ToTable("PackagingInventoryDocumentItems");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.PackagingInventoryDocumentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedAgent");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<DateTimeOffset>("Date");

                    b.Property<string>("DeletedAgent");

                    b.Property<string>("DeletedBy");

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<string>("DocumentNo")
                        .HasMaxLength(32);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(128);

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(128);

                    b.Property<string>("Remark")
                        .HasMaxLength(1024);

                    b.Property<string>("Status")
                        .HasMaxLength(32);

                    b.Property<string>("Storage")
                        .HasMaxLength(1024);

                    b.Property<int>("StorageId");

                    b.HasKey("Id");

                    b.ToTable("PackagingInventoryDocuments");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.ProductPackagingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Code")
                        .HasMaxLength(32);

                    b.Property<string>("Composition")
                        .HasMaxLength(128);

                    b.Property<string>("Construction")
                        .HasMaxLength(128);

                    b.Property<string>("CreatedAgent");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("Currency")
                        .HasMaxLength(1024);

                    b.Property<int>("CurrencyId");

                    b.Property<string>("DeletedAgent");

                    b.Property<string>("DeletedBy");

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<string>("Description")
                        .HasMaxLength(1024);

                    b.Property<string>("Design")
                        .HasMaxLength(128);

                    b.Property<string>("Grade")
                        .HasMaxLength(32);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<string>("Lot")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("PackagingCode");

                    b.Property<decimal>("Price");

                    b.Property<string>("ProductType")
                        .HasMaxLength(32);

                    b.Property<string>("SKU")
                        .HasMaxLength(1000);

                    b.Property<string>("SKUId")
                        .HasMaxLength(128);

                    b.Property<string>("Tags")
                        .HasMaxLength(512);

                    b.Property<string>("UOM")
                        .HasMaxLength(1024);

                    b.Property<int>("UOMId");

                    b.Property<string>("Width")
                        .HasMaxLength(128);

                    b.Property<string>("WovenType")
                        .HasMaxLength(128);

                    b.Property<string>("YarnType1")
                        .HasMaxLength(128);

                    b.Property<string>("YarnType2")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("ProductPackagings");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.ProductSKUModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Code")
                        .HasMaxLength(32);

                    b.Property<string>("Composition")
                        .HasMaxLength(128);

                    b.Property<string>("Construction")
                        .HasMaxLength(128);

                    b.Property<string>("CreatedAgent");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("Currency")
                        .HasMaxLength(1024);

                    b.Property<int>("CurrencyId");

                    b.Property<string>("DeletedAgent");

                    b.Property<string>("DeletedBy");

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<string>("Description")
                        .HasMaxLength(1024);

                    b.Property<string>("Design")
                        .HasMaxLength(128);

                    b.Property<string>("Grade")
                        .HasMaxLength(32);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<string>("Lot")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<decimal>("Price");

                    b.Property<string>("ProductType")
                        .HasMaxLength(32);

                    b.Property<string>("SKUCode")
                        .HasMaxLength(32);

                    b.Property<string>("SKUId")
                        .HasMaxLength(128);

                    b.Property<string>("Tags")
                        .HasMaxLength(512);

                    b.Property<string>("UOM")
                        .HasMaxLength(1024);

                    b.Property<int>("UOMId");

                    b.Property<string>("Width")
                        .HasMaxLength(128);

                    b.Property<string>("WovenType")
                        .HasMaxLength(128);

                    b.Property<string>("YarnType1")
                        .HasMaxLength(128);

                    b.Property<string>("YarnType2")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("ProductSKUs");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.SKUInventoryDocumentItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedAgent");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent");

                    b.Property<string>("DeletedBy");

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<decimal>("Quantity");

                    b.Property<string>("Remark")
                        .HasMaxLength(1024);

                    b.Property<string>("SKU")
                        .HasMaxLength(1024);

                    b.Property<int>("SKUId");

                    b.Property<int>("SkuInventoryDocumentId");

                    b.HasKey("Id");

                    b.HasIndex("SkuInventoryDocumentId");

                    b.ToTable("SKUInventoryDocumentItems");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.SKUInventoryDocumentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedAgent");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<DateTimeOffset>("Date");

                    b.Property<string>("DeletedAgent");

                    b.Property<string>("DeletedBy");

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<string>("DocumentNo")
                        .HasMaxLength(32);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(128);

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(128);

                    b.Property<string>("Remark")
                        .HasMaxLength(1024);

                    b.Property<string>("Status")
                        .HasMaxLength(32);

                    b.Property<string>("Storage")
                        .HasMaxLength(1024);

                    b.Property<int>("StorageId");

                    b.HasKey("Id");

                    b.ToTable("SKUInventoryDocuments");
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.PackagingInventoryDocumentItemModel", b =>
                {
                    b.HasOne("Com.Danliris.Service.Packing.Inventory.Data.Models.PackagingInventoryDocumentModel")
                        .WithMany("Items")
                        .HasForeignKey("PackagingIventoryDocumentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Com.Danliris.Service.Packing.Inventory.Data.Models.SKUInventoryDocumentItemModel", b =>
                {
                    b.HasOne("Com.Danliris.Service.Packing.Inventory.Data.Models.SKUInventoryDocumentModel")
                        .WithMany("Items")
                        .HasForeignKey("SkuInventoryDocumentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
